FROM jgoldfar/miniconda3:debian-bookworm-latest

# Make sure we don't get notifications we can't answer during building.
ENV DEBIAN_FRONTEND="noninteractive"
ENV LC_ALL="en_US.UTF-8"
ENV LANG="en_US.UTF-8"

LABEL maintainer "Jonathan Goldfarb <jgoldfar@gmail.com>"

RUN apt-get -qq update && \
    apt-get -qq -y install texlive && \
    apt-get -qq -y autoremove && \
    apt-get autoclean && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
