FROM jgoldfar/miniconda3:debian-bookworm-latest

# Make sure we don't get notifications we can't answer during building.
ENV DEBIAN_FRONTEND="noninteractive"
ENV LC_ALL="en_US.UTF-8"

LABEL maintainer "Jonathan Goldfarb <jgoldfar@gmail.com"

RUN dpkg-reconfigure locales && \
    apt-get -qq update && \
    apt-get --no-install-recommends -qq -y install texlive-full && \
    apt-get -qq -y autoremove && \
    apt-get autoclean
