name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push-full:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        imgtag: ['full', 'minimal']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Export Cache tokens using the Github runner shell
        uses: actions/github-script@v6
        with:
          script: |-
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])

      # https://github.com/docker/login-action
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${DOCKER_USER}
          password: ${DOCKER_TOKEN}

      - name: Build ${{ matrix.imgtag }} image, tagging with git SHA and latest
        id: build_image
        run: |
          docker build \
          -f Dockerfile.${{ matrix.imgtag }} \
          -t ${DOCKER_USER}/${REPO_NAME}:${{ matrix.imgtag }}-${GITHUB_SHA} \
          -t ${DOCKER_USER}/${REPO_NAME}:${{ matrix.imgtag }}-latest \
          -t ${DOCKER_USER}/${REPO_NAME}:${{ matrix.imgtag }} \
          .
        env:
          DOCKER_BUILDKIT: 1

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push --all-tags $DOCKER_USER/$REPO_NAME
