name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push-full:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        imgtag: ['full', 'minimal']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Login to Docker
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - name: Build ${{ matrix.imgtag }} image
        id: build_image
        run: |
          docker build -f Dockerfile.${{ matrix.imgtag }} -t ${DOCKER_USER}/${REPO_NAME}:${{ matrix.imgtag }}-${GITHUB_SHA} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag images for ${{ matrix.imgtag }}
        run: |
          docker tag ${DOCKER_USER}/$REPO_NAME:${{ matrix.imgtag }}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}-latest
          docker tag ${DOCKER_USER}/$REPO_NAME:${{ matrix.imgtag }}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}
          docker push $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}-latest
